<#import "/spring.ftl" as spring/>

<!DOCTYPE html>
<html>
<head>
    <title>Teacher</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="static/bootstrap.min.css">
</head>
<body>
<div>
    <h2>Students</h2>
    <hr/>
    <a href="/teachers/new-teachers">
        <button type="submit">Add new teacher</button>
    </a>
    <br/><br/>
    <div>
        <div>
            <div>Students</div>
        </div>
        <div>
            <table>
                <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Personal ID</th>
                    <th>Main subject</th>
                </tr>
                <#if (teachers?? && teachers?size != 0)>
                <#list teachers as teacher>
                <tr>
                    <td>${teacher.FirstName}</td>
                    <td>${teacher.LastName}</td>
                    <td>${teacher.TeacherID}</td>
                    <td>${teacher.PrimarySubject}</td>
                    <td>
                        <a href="/teachers/edit/${teacher.id?string('000000')}">Edit</a>
                    </td>
                    <td>
                        <a href="/teachers/delete/${teacher.id?string('0000000')}">Delete</a>
                    </td>
                </tr>
            </#list>
            <#else>
            No teachers registered yet
        </#if>
        </table>
    </div>
</div>
</div>
</body>
</html>
